travis:
  secure:
    BINSTAR_TOKEN: BUNmI0OR99AV74pwWPlivgNPonsBUyfaG0Pq8b1ymbCCLg3U8hXwla3vZ+IVczZftDgCOMU74CynoksXUYwgM/tWIWe6PrOBhthv+voXul7LbMTEAKMQWkZcBD+emCH9SkhoKDVgaTLwWJfsuPjYIdijbfZQxSaJxkJpMmx17LnQv8czk6BFG7hxhaXWknZ2jINfpuFrWuQWAakgKU6e/XVdErmzUP1FlC9opnp2IygFKAeDGx5+2Cd324ou6qt4j4WIuBOmkJhz++659165mq9ebW/0W7wfPLnlKn7nWWou2k4obCYQE1h97dws6ePzdlfoD8hQZG0XHW4hSF9Vd3fCs36HYiawncugy8/qwdBnGvG6dQAXbtIUhSAoQFrYqOTpFJl/z1YZgyz6yZsTDcoIV6Jja91BAmYX10UIR24vVdPN8SQMtqVxL5/LCtbYrK/gAsOraQKMSh9i3QYJvF9t4DHf+JGJXLjcSgpvegzpkMCZeOlvtxdjDTro1b0ixG/ir4Rr6vyFKa+HRzuzJZPJ66rGF48lYqjJhn/1zoWXcMnz+ngygJ0FL2liDPfLCxgbuU8zzvP0iMQVSpNvUTpGMNFqqRjytQdrlhlLEZ9BE2Vqj4l+uLxwxfpkYoH6R8zOtCqT8t42uMXsd5qFr8q7TY6eK+S+ucfjqcN/72M=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
