travis:
  secure:
    BINSTAR_TOKEN: IooXPHxdJ0i5fi72Ai2eAWt2F8vFpk2eKbWiXa4hbO5lpAKw3dn0PV4jaaZkG0/XQmdi6orWAhGrdDPtEYTUkA6reDCW/RWZ6AxALVi0K6Jhq6ObDsqIkYTYgG/zBMqCKdw3GfjEPuliMvEc5udBIwyeCF74WV3qRmwIX/Fr8YIG3mUri2zfp4/F7t2m+I55360NbB4v6yA9ntAM9yaAPe4hxYSEyIJ0TvhMHy/geshl0M5zWShZ/UmvahHwQn53NYUZ/H1/62IpbNJp9vUpbRQ7prj76x7Pqw+Sh3yvqnKuMOqQfk1P/K/lDkUq7h4RpW/ztUK9kKpAbK+ggU5Ezawk3QwXElJXOzqVSOBbySJ2OGENEnBhq3uX1/43Wx5Tf2LzNrZ1n61UqCkh+YNOyhTOsBvci+pUOHf53EFSZsRdTu85XsCWyFlbY8Ykep5qRnGen83SK+Vf3QKTQ1LJHeJtOfckX/7ctCP1xUXtS+1rNe6Kp8XJALaTm1ZVBgZr9RPDZGZd/oV330esPQ/oJ3Es+jjAsVdIrTx8fPGd6jcC6OUwBVTLE5NiB+z5Uj3Y5fI/5ZWsKXkxXJ0A3vILCe483V34qBNYzxAuiS4u4I0hI9VFqrtrH+dnaks4YtErHh2L7oFwtbuUOxWHOAqq1qEr2PnIZs2woQ8NN2Sz3s0=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
