travis:
  secure:
    BINSTAR_TOKEN: K84BilsBsPQv2G6OboE5zgS1CV8kP9J8EoxO2TF/58U4RuzfwLUOno+P8WtOcNj9GiVObye6Fmuy59e4fdPqHc+6NpuO+zolKyk/cJebdAWwNh5HjCf8DRx7Z4Y1+7k5Y5rH2TlAjbcYMcTa50hNF4a5hVNCKEmqOk4ft0GQvhmOptsIzxVk3Zs2vBBOzwWwVcJzetHPweu41liGkn9TcbPjKHGUKe5lyu13neuVV2244WKjKlFHNyfUDLxKOJcpiOJAo8H1Nbjv6JPXInveZAppbXrh8sIS94EzXwSQ+tQf5MLb6SWfDbW3wJlk0Sr3/mwKgqkXyae8F/dBbUERHM7LQ4ggpgsTEs4on6Yk9kX2zERJvOimRajFGjzMYp2oKfvD2oPUGhXKvPfe590MamuUkpJpB7AWSpI/hc0J46XZeSJ+tBuo+5vYWR5QwPwT1K6JGUlyN0ayt8AZjVFfr//uvgfwrji/6fsBDaG28HdtEGKNBpIB/4UlhXjbpUFH4c8f+LgQkupwb5wKdXVCjZEo4+42u/CAPYrqujjsSVb4Fmf6TsA84tIoSF07PPqwgv1VWcahFrR36AKwTW8x9IjlgI7aps3YgaBqsHfi/xmYFv0AIWiY8gP9BEAN+D98kVhn/QH+F/zWysvy7N0chD0B0TcGCh2NrngkXS5SMVg=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
